"""
Built-in disease-symptom dataset (mirrors Kaggle kaushi268 structure).
This allows the app to work WITHOUT downloading the Kaggle CSV.
Replace/augment with the real CSV for better accuracy.
"""

# All 132 symptoms (exact column names from Kaggle dataset)
ALL_SYMPTOMS = [
    'itching','skin_rash','nodal_skin_eruptions','continuous_sneezing','shivering','chills',
    'joint_pain','stomach_pain','acidity','ulcers_on_tongue','muscle_wasting','vomiting',
    'burning_micturition','spotting_urination','fatigue','weight_gain','anxiety',
    'cold_hands_and_feets','mood_swings','weight_loss','restlessness','lethargy',
    'patches_in_throat','irregular_sugar_level','cough','high_fever','sunken_eyes',
    'breathlessness','sweating','dehydration','indigestion','headache','yellowish_skin',
    'dark_urine','nausea','loss_of_appetite','pain_behind_the_eyes','back_pain',
    'constipation','abdominal_pain','diarrhoea','mild_fever','yellow_urine',
    'yellowing_of_eyes','acute_liver_failure','fluid_overload','swelling_of_stomach',
    'swelled_lymph_nodes','malaise','blurred_and_distorted_vision','phlegm',
    'throat_irritation','redness_of_eyes','sinus_pressure','runny_nose','congestion',
    'chest_pain','weakness_in_limbs','fast_heart_rate','pain_during_bowel_movements',
    'pain_in_anal_region','bloody_stool','irritation_in_anus','neck_pain','dizziness',
    'cramps','bruising','obesity','swollen_legs','swollen_blood_vessels',
    'puffy_face_and_eyes','enlarged_thyroid','brittle_nails','swollen_extremeties',
    'excessive_hunger','extra_marital_contacts','drying_and_tingling_lips','slurred_speech',
    'knee_pain','hip_joint_pain','muscle_weakness','stiff_neck','swelling_joints',
    'movement_stiffness','spinning_movements','loss_of_balance','unsteadiness',
    'weakness_of_one_body_side','loss_of_smell','bladder_discomfort','foul_smell_of_urine',
    'continuous_feel_of_urine','passage_of_gases','internal_itching','toxic_look_typhos',
    'depression','irritability','muscle_pain','altered_sensorium','red_spots_over_body',
    'belly_pain','abnormal_menstruation','dischromic_patches','watering_from_eyes',
    'increased_appetite','polyuria','family_history','mucoid_sputum','rusty_sputum',
    'lack_of_concentration','visual_disturbances','receiving_blood_transfusion',
    'receiving_unsterile_injections','coma','stomach_bleeding','distention_of_abdomen',
    'history_of_alcohol_consumption','fluid_overload_2','blood_in_sputum',
    'prominent_veins_on_calf','palpitations','painful_walking','pus_filled_pimples',
    'blackheads','scurring','skin_peeling','silver_like_dusting','small_dents_in_nails',
    'inflammatory_nails','blister','red_sore_around_nose','yellow_crust_ooze',
]

# 42 diseases with symptom lists
DISEASE_SYMPTOM_MAP = {
    'Fungal infection': ['itching','skin_rash','nodal_skin_eruptions','dischromic_patches'],
    'Allergy': ['continuous_sneezing','shivering','chills','watering_from_eyes'],
    'GERD': ['stomach_pain','acidity','ulcers_on_tongue','vomiting','cough','chest_pain'],
    'Chronic cholestasis': ['itching','vomiting','yellowish_skin','nausea','loss_of_appetite','abdominal_pain','yellowing_of_eyes'],
    'Drug Reaction': ['itching','skin_rash','stomach_pain','burning_micturition','spotting_urination'],
    'Peptic ulcer diseae': ['vomiting','indigestion','loss_of_appetite','abdominal_pain','passage_of_gases','internal_itching'],
    'AIDS': ['muscle_wasting','patches_in_throat','high_fever','extra_marital_contacts','fatigue'],
    'Diabetes': ['fatigue','weight_loss','restlessness','lethargy','irregular_sugar_level','blurred_and_distorted_vision','obesity','excessive_hunger','increased_appetite','polyuria'],
    'Gastroenteritis': ['vomiting','sunken_eyes','dehydration','diarrhoea'],
    'Bronchial Asthma': ['fatigue','cough','high_fever','breathlessness','family_history','mucoid_sputum'],
    'Hypertension': ['headache','chest_pain','dizziness','loss_of_balance','lack_of_concentration'],
    'Migraine': ['acidity','indigestion','headache','blurred_and_distorted_vision','excessive_hunger','stiff_neck','depression','irritability','visual_disturbances'],
    'Cervical spondylosis': ['back_pain','weakness_in_limbs','neck_pain','dizziness','loss_of_balance'],
    'Paralysis (brain hemorrhage)': ['vomiting','headache','weakness_of_one_body_side','altered_sensorium'],
    'Jaundice': ['itching','vomiting','fatigue','weight_loss','high_fever','yellowish_skin','dark_urine','abdominal_pain'],
    'Malaria': ['chills','vomiting','high_fever','sweating','headache','nausea','diarrhoea','muscle_pain'],
    'Chicken pox': ['itching','skin_rash','fatigue','lethargy','high_fever','headache','loss_of_appetite','mild_fever','swelled_lymph_nodes','malaise','red_spots_over_body'],
    'Dengue': ['skin_rash','chills','joint_pain','vomiting','fatigue','high_fever','headache','nausea','loss_of_appetite','pain_behind_the_eyes','back_pain','muscle_pain','red_spots_over_body'],
    'Typhoid': ['chills','vomiting','fatigue','high_fever','headache','nausea','constipation','abdominal_pain','diarrhoea','toxic_look_typhos','belly_pain'],
    'hepatitis A': ['joint_pain','vomiting','yellowish_skin','dark_urine','nausea','loss_of_appetite','abdominal_pain','diarrhoea','mild_fever','yellowing_of_eyes','muscle_pain'],
    'Hepatitis B': ['itching','fatigue','lethargy','yellowish_skin','dark_urine','loss_of_appetite','abdominal_pain','yellow_urine','yellowing_of_eyes','malaise','receiving_blood_transfusion','receiving_unsterile_injections'],
    'Hepatitis C': ['fatigue','yellowish_skin','nausea','loss_of_appetite','family_history'],
    'Hepatitis D': ['joint_pain','vomiting','fatigue','yellowish_skin','dark_urine','nausea','loss_of_appetite','abdominal_pain','yellowing_of_eyes'],
    'Hepatitis E': ['joint_pain','vomiting','fatigue','high_fever','yellowish_skin','dark_urine','nausea','loss_of_appetite','abdominal_pain','acute_liver_failure','coma','stomach_bleeding'],
    'Alcoholic hepatitis': ['vomiting','yellowish_skin','abdominal_pain','swelling_of_stomach','history_of_alcohol_consumption','fluid_overload','renal_failure'],
    'Tuberculosis': ['chills','vomiting','fatigue','weight_loss','cough','high_fever','sweating','loss_of_appetite','mild_fever','swelled_lymph_nodes','malaise','phlegm','blood_in_sputum','rusty_sputum'],
    'Common Cold': ['continuous_sneezing','chills','fatigue','cough','high_fever','headache','swelled_lymph_nodes','malaise','phlegm','throat_irritation','redness_of_eyes','sinus_pressure','runny_nose','congestion','chest_pain','loss_of_smell','muscle_pain'],
    'Pneumonia': ['chills','fatigue','cough','high_fever','breathlessness','sweating','malaise','phlegm','chest_pain','fast_heart_rate','rusty_sputum'],
    'Dimorphic hemmorhoids(piles)': ['constipation','pain_during_bowel_movements','pain_in_anal_region','bloody_stool','irritation_in_anus'],
    'Heart attack': ['vomiting','breathlessness','sweating','chest_pain','weakness_in_limbs'],
    'Varicose veins': ['fatigue','cramps','bruising','obesity','swollen_legs','swollen_blood_vessels','prominent_veins_on_calf'],
    'Hypothyroidism': ['fatigue','weight_gain','cold_hands_and_feets','mood_swings','lethargy','puffy_face_and_eyes','enlarged_thyroid','brittle_nails','swollen_extremeties','depression','dryness_and_tingling_lips'],
    'Hyperthyroidism': ['fatigue','mood_swings','weight_loss','restlessness','sweating','diarrhoea','fast_heart_rate','excessive_hunger','muscle_weakness','irritability','abnormal_menstruation'],
    'Hypoglycemia': ['vomiting','fatigue','anxiety','sweating','headache','nausea','blurred_and_distorted_vision','excessive_hunger','slurred_speech','irritability','drying_and_tingling_lips','palpitations'],
    'Osteoarthritis': ['joint_pain','neck_pain','knee_pain','hip_joint_pain','swelling_joints','painful_walking'],
    'Arthritis': ['muscle_weakness','stiff_neck','swelling_joints','movement_stiffness','loss_of_appetite'],
    '(vertigo) Paroymsal Positional Vertigo': ['vomiting','headache','nausea','spinning_movements','loss_of_balance','unsteadiness'],
    'Acne': ['skin_rash','pus_filled_pimples','blackheads','scurring'],
    'Urinary tract infection': ['burning_micturition','bladder_discomfort','foul_smell_of_urine','continuous_feel_of_urine'],
    'Psoriasis': ['skin_rash','joint_pain','skin_peeling','silver_like_dusting','small_dents_in_nails','inflammatory_nails'],
    'Impetigo': ['skin_rash','high_fever','blister','red_sore_around_nose','yellow_crust_ooze'],
}

# Disease → specialist mapping
DISEASE_SPECIALIST = {
    'Fungal infection':             'Dermatologist',
    'Allergy':                      'General Physician',
    'GERD':                         'Gastroenterologist',
    'Chronic cholestasis':          'Gastroenterologist',
    'Drug Reaction':                'General Physician',
    'Peptic ulcer diseae':          'Gastroenterologist',
    'AIDS':                         'Infectious Disease',
    'Diabetes':                     'Endocrinologist',
    'Gastroenteritis':              'Gastroenterologist',
    'Bronchial Asthma':             'Pulmonologist',
    'Hypertension':                 'Cardiologist',
    'Migraine':                     'Neurologist',
    'Cervical spondylosis':         'Orthopedic',
    'Paralysis (brain hemorrhage)': 'Neurologist',
    'Jaundice':                     'Hepatologist',
    'Malaria':                      'Infectious Disease',
    'Chicken pox':                  'General Physician',
    'Dengue':                       'Infectious Disease',
    'Typhoid':                      'Infectious Disease',
    'hepatitis A':                  'Hepatologist',
    'Hepatitis B':                  'Hepatologist',
    'Hepatitis C':                  'Hepatologist',
    'Hepatitis D':                  'Hepatologist',
    'Hepatitis E':                  'Hepatologist',
    'Alcoholic hepatitis':          'Hepatologist',
    'Tuberculosis':                 'Pulmonologist',
    'Common Cold':                  'General Physician',
    'Pneumonia':                    'Pulmonologist',
    'Dimorphic hemmorhoids(piles)': 'General Physician',
    'Heart attack':                 'Cardiologist',
    'Varicose veins':               'General Physician',
    'Hypothyroidism':               'Endocrinologist',
    'Hyperthyroidism':              'Endocrinologist',
    'Hypoglycemia':                 'Endocrinologist',
    'Osteoarthritis':               'Orthopedic',
    'Arthritis':                    'Rheumatologist',
    '(vertigo) Paroymsal Positional Vertigo': 'ENT Specialist',
    'Acne':                         'Dermatologist',
    'Urinary tract infection':      'Urologist',
    'Psoriasis':                    'Dermatologist',
    'Impetigo':                     'Dermatologist',
}

# Short descriptions for each disease
DISEASE_INFO = {
    'GERD': 'Gastroesophageal reflux disease — chronic acid reflux causing heartburn and regurgitation.',
    'Diabetes': 'A metabolic disorder characterized by high blood sugar levels due to insufficient insulin.',
    'Hypertension': 'High blood pressure — a long-term medical condition where blood pressure is persistently elevated.',
    'Malaria': 'A mosquito-borne infectious disease caused by Plasmodium parasites.',
    'Dengue': 'A mosquito-transmitted viral infection causing flu-like symptoms and potentially fatal complications.',
    'Tuberculosis': 'A potentially serious infectious disease mainly affecting the lungs, caused by Mycobacterium tuberculosis.',
    'Common Cold': 'A viral infection of the upper respiratory tract, typically caused by rhinovirus.',
    'Pneumonia': 'Infection that inflames air sacs in one or both lungs, which may fill with fluid.',
    'Heart attack': 'Occurs when blood flow to the heart is severely reduced or blocked.',
    'Migraine': 'A neurological disease with recurrent episodes of moderate to severe headache.',
    'Fungal infection': 'Skin infection caused by dermatophyte fungi, presenting as itchy, scaly skin.',
    'Acne': 'A skin condition that occurs when hair follicles become plugged with oil and dead skin cells.',
    'Urinary tract infection': 'An infection in any part of the urinary system — kidneys, bladder, ureters, urethra.',
}
