# Generated by Django 4.2.16 on 2026-06-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_appointmentslot_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("booking", "Booking Help"),
                            ("diagnosis", "Diagnosis Query"),
                            ("refund", "Disputes & Refunds"),
                            ("other", "Other Support"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
