# Generated by Django 4.2.16 on 2026-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_appointment_doctor_notes_appointment_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="razorpay_refund_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="appointment",
            name="refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refund_initiated", "Refund Initiated"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
