# Generated by Django 4.2.16 on 2026-06-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_appointment_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[("in_person", "In Person"), ("video", "Video Consult")],
                default="in_person",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancellation_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="queue_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="appointment",
            name="refund_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="video_room_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="video_room_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refund_pending", "Refund Pending"),
                    ("refunded", "Refunded"),
                    ("no_refund", "No Refund"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("payment_done", "Payment Done"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
