# Generated by Django 4.2.16 on 2026-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_appointment_appointment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
