# Generated by Django 4.2.16 on 2026-03-06 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("mobile_no", models.CharField(blank=True, max_length=15)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="patients/"),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField(blank=True, null=True)),
                ("img", models.ImageField(blank=True, null=True, upload_to="doctors/")),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("mobile_no", models.CharField(blank=True, max_length=15)),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("General Physician", "General Physician"),
                            ("Cardiologist", "Cardiologist"),
                            ("Gastroenterologist", "Gastroenterologist"),
                            ("Neurologist", "Neurologist"),
                            ("Endocrinologist", "Endocrinologist"),
                            ("Pulmonologist", "Pulmonologist"),
                            ("Orthopedic", "Orthopedic"),
                            ("Dermatologist", "Dermatologist"),
                            ("Urologist", "Urologist"),
                            ("Ophthalmologist", "Ophthalmologist"),
                            ("ENT Specialist", "ENT Specialist"),
                            ("Psychiatrist", "Psychiatrist"),
                            ("Pediatrician", "Pediatrician"),
                            ("Gynecologist", "Gynecologist"),
                            ("Oncologist", "Oncologist"),
                            ("Rheumatologist", "Rheumatologist"),
                            ("Nephrologist", "Nephrologist"),
                            ("Hematologist", "Hematologist"),
                            ("Hepatologist", "Hepatologist"),
                            ("Infectious Disease", "Infectious Disease Specialist"),
                        ],
                        max_length=100,
                    ),
                ),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("experience_yrs", models.PositiveIntegerField(default=0)),
                ("bio", models.TextField(blank=True)),
                ("hospital_name", models.CharField(blank=True, max_length=200)),
                (
                    "fee",
                    models.PositiveIntegerField(
                        default=0, help_text="Consultation fee in INR"
                    ),
                ),
                ("available_from", models.TimeField(blank=True, null=True)),
                ("available_to", models.TimeField(blank=True, null=True)),
                ("rating", models.FloatField(default=0.0)),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                (
                    "video_consult",
                    models.BooleanField(
                        default=True, help_text="Offers video consultation"
                    ),
                ),
                (
                    "chat_consult",
                    models.BooleanField(
                        default=True, help_text="Offers chat consultation"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
