# Generated by Django 4.2.16 on 2026-06-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="medical_degree",
            field=models.FileField(blank=True, null=True, upload_to="doctor_degrees/"),
        ),
    ]
