# Generated by Django 4.2.16 on 2026-06-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_doctorprofile_medical_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="aadhaar_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="aadhaar/doctors/"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="bank_account_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="bank_ifsc",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="payment_setup_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="upi_id",
            field=models.CharField(
                blank=True, help_text="UPI ID e.g. name@upi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="aadhaar_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="aadhaar/patients/"
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="aadhaar_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="is_aadhaar_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="selfie_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="selfies/patients/"
            ),
        ),
    ]
