# Generated by Django 4.2.16 on 2026-06-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_doctorprofile_aadhaar_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="medical_degree",
        ),
    ]
