# Generated by Django 4.2.16 on 2026-06-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_medical_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="video_consult_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="video_consult_fee",
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
